name: prueba
description: "A unified Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_datetime_picker: ^1.5.1
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  geolocator: ^13.0.2
  geocoding: ^2.0.5
  http: ^1.2.2
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  font_awesome_flutter: 10.7.0
  google_fonts: 6.1.0
  intl: 0.19.0
  page_transition: 2.1.0
  provider: 6.1.2
  shared_preferences: 2.3.2
  sqflite: 2.3.3+1
  timeago: 3.6.1
  url_launcher: 6.3.0
  flutter_localizations:
    sdk: flutter
  from_css_color: 2.0.0
  go_router: 12.1.3
  json_path: 0.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - Logo-CTR.png
    - Logo-CTR1.png